### ISSUE TITLE
When there are specific images in the document, exporting results in a blank page. The page functions normally when the image is deleted.

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#332]
<img width="1770" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/31ea52df-6077-47b1-8151-de5d4bec1e8f">

<img width="1748" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/8d0a2820-f129-4abe-af7f-6f90bd417dfd">

[Exp.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/14139026/Exp.zip)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/b1d52292-0000-49bb-ab1b-bda59bf0788a)

<img width="1768" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/68c8183e-8803-414b-99fb-d7f1d8dfc91c">

When I delete this image, the export works fine, which is really strange. I tried for a while before discovering that this image was affecting the export

**Comment by KosmosisDire** [comment]
This is pretty weird, I'll test it and see what I can do

**Comment by KosmosisDire** [comment]
Also as a side note, I fixed the export speed of the HTML Documents export mode in 1.8.0-8b. Turns out there actually _was_ a bug causing it to be much slower.

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/1590cbb0-891d-46a6-8232-4fd4e65e88b0)

<img width="1800" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/4447408d-cf47-4c3c-901d-a25acd6035ef">

I found that I can reproduce this bug when my image is in another directory.

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/91b04d27-76f0-4723-9865-ccde43f388ea)

<img width="1755" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/08e8c7df-481b-4aab-bc52-8dd8a3beb803">

When I directly copy the image link code from the folder1_note1 editing view to the folder2_note1 editing view, I found that it can be displayed correctly in Obsidian. However, when exporting folder2_note1, it still shows up as blank.


In my actual document writing process, I often need to copy repetitive content, including images. I've noticed that when copying content to Obsidian, the file paths remain the same and the images can still be displayed correctly. I'm not sure what processing Obsidian does to achieve this.

**Comment by KosmosisDire** [comment]
> By the way, what are these error messages? I didn't quite understand them.
This is something I am working to fix, and thus I have started logging it (it was doing the before too but it wasn't being logged)
Basically your theme css has a bunch of images included in the css file and the plugin find and fetches those images so they can be included with the website. It's not an error you need to worry about at all.

As far as the image bug, it's definetly a weird bug and not one that was happening before as far as I know. But I am working on fixing it.

**Comment by KosmosisDire** [comment]
Hey, this should be fixed in 1.8.0-9b, could you try it out and let me know. Thanks

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/646bc597-12e5-4df8-b95f-a945e65e8e73)

<img width="1781" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/3b134c65-9229-4a11-a04b-83771a27661a">

This issue has not been resolved, I think it is due to incorrect image paths. However, even if the image paths are incorrect in V1.6.0, the images can still be displayed correctly.

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/8bc03492-d50a-481a-82ab-bca976594d22)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/bfe5baa9-7603-4252-b042-eb251d536c09)

I tried it, and even with the correct path, this issue still exists. The images are not displayed correctly

**Comment by KosmosisDire** [comment]
I was able to reproduce the problem before using your example but I am no longer able to reproduce it at all. Have you tried deleting the export and reexporting everything and confirmed you are using the latest version?

**Comment by KosmosisDire** [comment]
What is happening there looks like a different issue actually, does the image cause all other note contents to dissapear still? Or does it show everything except the image?

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/92f18820-f83b-45fe-b5cf-93a4b98111e7)

I believe it is specific logic for these two options. If I remove "NOTE1", it can be displayed correctly, but it doesn't work if I remove "NOTE2".

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/03e20f79-d416-41c8-8c36-a53e4ebae558)
I uninstalled the old version first and then copied the folder of the new version into the plugin directory. I think my operation is correct

**Comment by KosmosisDire** [comment]
I cannot reproduce this anymore. Here is an example: https://nathang.dev/fileshare/test-vault/tests/media.html
It included images that are forward and backwards relative to the file and ones in different folder or even outside the vault. All of them work fine for me.

I am also testing with your original setup and cannot reproduce it:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/ea77152e-2b24-40cb-84f8-5d8921c2c6cd)

**Comment by KosmosisDire** [comment]
I will recreate your second scenario and try to reproduce it that way

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/80216c10-2701-4620-981d-d5ee6c399182)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/312fadf1-a371-4d90-b8e7-207305b97898)

In fact, the images are located in the "media" directory of NOTE1. However, in Obsidian, I directly used the image links from NOTE1 and placed them in NOTE2. The path in NOTE2 is incorrect, but surprisingly, they are still displayed correctly in Obsidian. In version 1.6.0, I discovered that even with incorrect paths, successful export is still possible. Therefore, I am raising this issue to see if it is something that you would consider resolving in the development of this plugin.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2dec9dd1-6d2a-45d4-a91b-3377fff7787b)

When I try to use the correct relative path, the images still do not display correctly.

According to the normal logic, the incorrect path should not display the images correctly, and this is true. However, even after changing to use relative paths, the images still do not appear when exporting. This may be because NOTE1 and NOTE2 are located in different folders, and when exporting, only one of the folders is selected, causing the issue.

**Comment by KosmosisDire** [comment]
Obsidian doesn't need an image path, just the image name. It finds the image closest to the file with that name. I am already handling this the same way (which is why this worked before)

**Comment by KosmosisDire** [comment]
But for me the image is never being downloaded. Did you say that the image is being downloaded for you? But just not displaying? Can you check if the image actually gets downloaded (try deleting everything first just to make sure)

**Comment by zhoulonghao520** [comment]
I have checked the media folder. During the export process, the images were not stored in that folder.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/7427ea3c-4c50-4412-9a23-703f97fbfd3a)

**Comment by KosmosisDire** [comment]
So it is correctly stored in the `note1/media/` folder?

**Comment by KosmosisDire** [comment]
Okay so I actually reexported everything and I can no longer reproduce it

**Comment by KosmosisDire** [comment]
https://nathang.dev/fileshare/exp-test/note-1/note-1.html

**Comment by zhoulonghao520** [comment]
YES note1/media/ 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/9d9e2ad5-1382-41e7-bf59-72020df7a826)

photos is OK

**Comment by KosmosisDire** [comment]
Obviously there is still a problem, but it seems like re exporting just fixed it. Maybe it has something to do with a first time export or when obsidian has first loaded. I am not sure. Or maybe it is chance.

**Comment by zhoulonghao520** [comment]
When NOTE1 and NOTE2 are in the same root directory, it can be displayed correctly. It is only when they are in different root directories that the display becomes abnormal.

**Comment by KosmosisDire** [comment]
This is also what I noticed, however it doesn't seem to continue to be a problem after a re-export. Is this also the case for you or does this happen every time you export?

**Comment by KosmosisDire** [comment]
Does this problem occur for you using version 1.7.3?

**Comment by zhoulonghao520** [comment]
obsidian V1.5.3

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/188074d5-2d8f-4773-b479-ca2ec0746a14)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/6643e524-e76a-4605-9223-3fa1f0017d14)


v1.7.3 IS OIK

In V1.7.3, multiple exports were tested and this issue was not found.

**Comment by aubreyz** [comment]
This may be irrelevant but those images are somewhat unusual in that the JFIF resolution metadata is malformed (i.e blank) How were they created?

**Comment by KosmosisDire** [comment]
Hey, can you verify this is fixed in the beta version 1.8.0-10b?

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
